### ISSUE TITLE
How did you deal with the different number of joints in datasets?

### ISSUE THREAD

**Issue by divyanshusharma1709** [shanice-l/st-cubism#36]
Hi! Congratulations on your fantastic work getting published! It is a very interesting read!

I have a question: When conducting experiments between the NTU and Kinetics-Skeleton dataset, how did you deal with the different number of joints in the two datasets?

For example, number of joints in:

NTU: 25
Kinetics-Skeleton: 18

Is the HCN backbone inherently able to handle them, or did you modify the skeletons?

Thanks!

**Comment by shanice-l** [comment]
Hi, thanks for your interest in our work!

We made some modifications to the skeleton. Specifically, based on the joint definition in the NTU paper, we removed the joints ``middle of the spine'', ``left hand'', ``right hand'', ``left ankle'', ``right ankle'', ``left thumb'' and ``right thumb'' for num_joint=18.

**Comment by divyanshusharma1709** [comment]
Thank you replying! Was there some logic behind removing these specific joints?

**Comment by shanice-l** [comment]
Since different datasets define different joints, we remove some specific joints to make the joint definition cross datasets roughly the same.
